env: local
http:
  host: localhost
  port: 4050
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

cache:
  ttl: 60s

db:
  host: ""
  login: "root"
  password: ""
  dbname: "portal"
  maxOpenConns: 25
  maxIdleConns: 25
  maxIdleTime: "15m"
smtp:
  host: "192.168.10.10"
  port: 1025
  username: ""
  password: ""
  sender: "Portal Admin <admin@sergeyem.ru>"
limiter:
  rps: 2
  burst: 4
  enabled: true
  ttl: 10m
cors:
  trustedOrigins: ["127.0.0.1"]
domain: "http://127.0.0.1"
email:
  sendWelcomeEmail: true
  templates:
    registrationEmail: "./templates/registration_email.html"
    ticketSuccessful: "./templates/ticket_successful.html"
    restorePasswordEmail: "./templates/password_reset.html"
  subjects:
    registrationEmail: "Спасибо за регистрацию, %s!"
    ticketSuccessful: "Тикет размещён успешно!"
    restorePassword: "Сброс пароля от клиентского портала"
vtiger:
  connection:
    url: "https://serv.itvolga.com/webservice.php"
    login: "admin"
    password: ""
    persistenceConnection: true
    maxRetries: 3
  business:
    emailField: "email"
    codeField: "code"
    supportEmail: "emelyanov86@list.ru"
    companyId: "23x1"
    clearCode: true
    defaultPagination: 20
    defaultUser: "19x1"
otp:
  issuer: "portal.itvolga.com"
  accountName: "info@itvolga.com"
  secretSize: 15
payment:
  stripe_key: ""
  stripe_public: ""