name: Go

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.0'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          go version

      - name: Get dependencies
        run: go mod download

      - name: Tidying
        run: go mod tidy

      - name: Verify dependencies
        run: go mod verify

      - name: Vendoring
        run: go mod vendor

      - name: Vetting
        run: go vet ./...

      - name: Run Staticcheck
        run: |
            go install honnef.co/go/tools/cmd/staticcheck@latest
            staticcheck ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -race -vet=off ./...

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: GOOS=linux GOARCH=amd64 go build -o=./bin/portal ./cmd/app

      - name: Deploy
        run: |
          scp ./bin/portal easylist@serv.sergeyem.ru:/home/easylist/portal/bin/portal
          ssh easylist@serv.sergeyem.ru 'chmod 777 /home/easylist/portal/bin/portal
#          ssh root@serv.sergeyem.ru 'sudo systemctl restart portal'
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
